# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Osyko Vitaly
title: QA Engeneer
email: vitoqae@gmail.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  VitoOsyko
linkedin_username: vitaly-osyko-09248a247
instagram_username: pokrovsky_vito
telegram_username: Pokrovsky_Vito
# twitter_username: facespics
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram link
  icon: fab fa-telegram (https://fontawesome.com/icons?d=gallery&m=free)
  url: https://t.me/Pokrovsky_Vito
- title: MyPortfolio
  icon: fab fa-google-drive (https://fontawesome.com/icons?d=gallery&m=free)
  url: https://drive.google.com/drive/folders/14wouMRFl7Py97EzI_cPdJZvvLyVFh4hy?usp=share_link

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Vitaly and I'm a QA Engeneer. Results-driven and strong attention-to-detail. Passionate about testing software applications. Unfortunately, I did not get inherited estates and capitals, therefore I am devilishly hardworking! Ability to learn quickly, often under high deadlines, to fully understand a new product or platform. Great problem solving skills and ability to perform work well in a team. I have experience in commercial projects where I have acquired teamwork and leadership skills. I know 4 words in French and 2 in Spanish (not counting the numbers)

  I am most skilled in: <mark>Bug localization</mark> and <mark>Eating Pizza</mark>

content:
  - title: Experience # Title for the section 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Outsourcing company ITX
        sub_title: QA Engeneer
        caption: September 2022 - Present
        link: https://www.linkedin.com/in/innadidenko/
        link_text: Reference - QA Manager Inna Didenko
        quote: >
           Solving 21st century problems by through endless testing in the name of creating game-changing products
        description: | # this will include new lines to allow paragraphs
         Every company needs a good quality assurance engineer and ITX is no exception. Testing can be difficult, but I play my part by ensuring the quality of the product and enjoy driving the fact that company appreciates my work which is:
         
         - UAT testing, functional testing
         - Web testing (prod Version: [capital.com](https://capital.com/) and [currency.com](https://currency.com/))
         - Mobile testing: (prod Version: app Investmate, app Crypto Price Widgets, app Liveness Check)
         - Localization, Cross-platform, Cross-browser, Smoke, Critical path, Regression testing, Re-testing, Ad-hoc
         - Testing and collecting ad impressions on financing platforms ([Investopedia](https://www.investopedia.com/), [FT](https://www.ft.com/), [Bloomberg](https://www.bloomberg.com/))
         - [Test documentation](https://drive.google.com/drive/folders/12BRNLBO7HZvBkDHRUMyQr2I7sAFId0Rz?usp=share_link): checklists, test cases, bug reports, test result reports 
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ksendzov QA course
        sub_title: QA Trainee
        caption: August 2022 - Present
        link: https://www.linkedin.com/in/vadim-ksendzov-74099837/
        link_text: Reference - Lead QA Vadim Ksendzov
        quote: >
          Per aspera ad astra... The difficult path from junior to commercial practice mentor
        description: | # this will include new lines to allow paragraphs
            After a long period of self-study, I decided to enroll in Vadim Ksendzov's courses. In addition to technical knowledge, in the flow of students, I acquired many <mark>soft skills:</mark>
            
           ![Soft Skills](images/chrome_eAR9BjKZab-transformed.png "SoftSkills")
            
            There were many interesting tasks on the course, the execution of which you can see in my repository on [GitHub](https://github.com/VitoOsyko) and my [Google Drive](https://drive.google.com/drive/folders/14wouMRFl7Py97EzI_cPdJZvvLyVFh4hy?usp=share_link).
            
            During the course, I learned a lot and acquired the following <mark>hard skills:</mark>
            
            - Testing Theory 
            - Analyzing and testing requirements 
            - Fiddler, Charles 
            - AppsFlyer 
            - Jira, YouTrack  
            - Git, GitHub 
            - DevTools (Google Chrome, FireFox, Opera) 
            - Postman 
            - SQL basics 
            - JS 
            - Terminal 
            - Android Studio 
            - HTML & CSS (YAML) 
            - 1C 
            - Jmetr

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")
    
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
